package cmd

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/piano-app/piano-cli/internal/api"
	"github.com/piano-app/piano-cli/internal/sshx"
	"github.com/spf13/cobra"
)

// Markers wrap the piano-managed block in ~/.ssh/config so future syncs
// can replace just our slice and leave the user's hand-written config
// alone. Anyone reading the file can immediately see who wrote what.
const (
	sshIncludeBegin = "# === BEGIN PIANO MANAGED — added by `piano ssh sync` ==="
	sshIncludeEnd   = "# === END PIANO MANAGED ==="
)

var sshCmd = &cobra.Command{
	Use:   "ssh",
	Short: "Manage SSH config for piano machines",
}

var sshSyncCmd = &cobra.Command{
	Use:   "sync",
	Short: "Write Host entries for every machine to ~/.ssh/config.d/piano",
	Long: `Rewrites ~/.ssh/config.d/piano with one Host stanza per running machine,
and adds an Include directive to ~/.ssh/config (idempotent).

Afterwards, ssh / VS Code Remote-SSH / Cursor / Windsurf can pick any
machine by host alias — e.g. "ssh feat-auth.piano".

Re-run any time the machine list changes. Removing a machine here does NOT
delete the machine itself; use "piano machine rm" for that.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		machines, err := client.MachineList()
		if err != nil {
			return err
		}

		// 1. Write ~/.ssh/config.d/piano.
		home, err := os.UserHomeDir()
		if err != nil {
			return err
		}
		dir := filepath.Join(home, ".ssh", "config.d")
		if err := os.MkdirAll(dir, 0o700); err != nil {
			return fmt.Errorf("mkdir %s: %w", dir, err)
		}
		blockPath := filepath.Join(dir, "piano")
		if err := os.WriteFile(blockPath, renderHostsBlock(machines, sshx.DefaultHost, sshx.DefaultPort), 0o600); err != nil {
			return fmt.Errorf("write %s: %w", blockPath, err)
		}

		// 2. Add `Include config.d/piano` to ~/.ssh/config if not already there.
		mainPath := filepath.Join(home, ".ssh", "config")
		if err := ensureInclude(mainPath); err != nil {
			return fmt.Errorf("update %s: %w", mainPath, err)
		}

		fmt.Printf("Wrote %d host entries to %s\n", len(machines), blockPath)
		return nil
	},
}

// renderHostsBlock turns the machine list into the body of config.d/piano.
// One Host stanza per machine, with two aliases: the friendly name and
// the daemon id. Both end in .piano so users can match `Host *.piano *`
// for common settings if they want.
func renderHostsBlock(machines []api.Machine, host string, port int) []byte {
	var b bytes.Buffer
	fmt.Fprintln(&b, "# Generated by `piano ssh sync` — do not edit by hand.")
	fmt.Fprintln(&b, "# Run `piano ssh sync` again to refresh; delete this file to disable.")
	fmt.Fprintln(&b)
	for _, m := range machines {
		alias := sanitizeAlias(m.DisplayName())
		idAlias := sanitizeAlias(m.ID)
		hosts := []string{idAlias + ".piano"}
		if alias != "" && alias != idAlias {
			hosts = append([]string{alias + ".piano"}, hosts...)
		}
		fmt.Fprintf(&b, "Host %s\n", strings.Join(hosts, " "))
		fmt.Fprintf(&b, "  HostName %s\n", host)
		fmt.Fprintf(&b, "  Port %d\n", port)
		fmt.Fprintf(&b, "  User %s\n", m.ID)
		fmt.Fprintln(&b, "  StrictHostKeyChecking accept-new")
		fmt.Fprintln(&b)
	}
	return b.Bytes()
}

// SSH host alias rules: no whitespace, no '?', no '*'. We're stricter for
// readability — only alnum, dot, hyphen, underscore.
var aliasUnsafe = regexp.MustCompile(`[^A-Za-z0-9._-]+`)

func sanitizeAlias(s string) string {
	s = strings.TrimSpace(s)
	s = aliasUnsafe.ReplaceAllString(s, "-")
	return strings.Trim(s, "-")
}

// ensureInclude prepends a marker block containing `Include config.d/piano`
// to ~/.ssh/config if our markers aren't already present. Idempotent:
// running it twice is a no-op on the second call.
func ensureInclude(path string) error {
	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	if bytes.Contains(existing, []byte(sshIncludeBegin)) {
		return nil
	}
	var out bytes.Buffer
	fmt.Fprintln(&out, sshIncludeBegin)
	fmt.Fprintln(&out, "Include config.d/piano")
	fmt.Fprintln(&out, sshIncludeEnd)
	if len(existing) > 0 {
		fmt.Fprintln(&out)
		out.Write(existing)
	}
	return os.WriteFile(path, out.Bytes(), 0o600)
}

func init() {
	sshCmd.AddCommand(sshSyncCmd)
	rootCmd.AddCommand(sshCmd)
}
