/**
 * Workflow Activities — DB side-effect helpers used by executeWorkflowWorkflow.
 *
 * The orchestrator workflow is pure orchestration (deterministic per
 * Temporal's contract). Anything touching Prisma / NATS lives here.
 *
 * Activities:
 *   - loadWorkflowDefinition: read the workflow row → typed Model.
 *   - plantUserNodes:         batch-create USER notes + edges, emit SSE.
 *   - createOptimisticPlaceholders:
 *                             batch-create RUNNING ASSISTANT placeholder
 *                             notes + edges, emit SSE. The Action child
 *                             workflow fills these in.
 *
 * **Idempotency.** Both batch activities accept pre-generated note + edge
 * ids from the workflow (Temporal's `uuid4()` is deterministic across
 * replays). Inserts use `createMany({ skipDuplicates: true })`, then we
 * re-load by id and re-emit SSE. On Temporal retry, the inserts are a
 * no-op, the re-load returns the same rows, and the canvas store already
 * dedupes SSE node-created events by id (LWW). No duplicates.
 *
 * AI is NOT here — workflow runs Action as a child workflow per cell, so
 * all AI logic (cache, system prompts, retry, MULTIPLE_CHILDREN fan-out)
 * is inherited from the existing Action pipeline untouched.
 */

import { services } from '../../services/init';
import { Workflow, Note, Edge, Canvas } from '@piano/shared';
import { emitNodeCreated } from '../../domains/action/shared';

export type PlantUserCell = {
  parentId: string;
  text: string;
  /** Index of this context within level.contexts — used for X-offset layout. */
  contextIdx: number;
};

const USER_BELOW_PARENT_Y = 220;
const PLACEHOLDER_BELOW_USER_Y = 220;

export async function loadWorkflowDefinition(workflowId: string): Promise<Workflow.Model | null> {
  const row = await services.prisma.workflow.findUnique({ where: { id: workflowId } });
  if (!row) return null;
  return {
    id: row.id,
    name: row.name,
    levels: Array.isArray(row.levels) ? (row.levels as unknown as Workflow.Level[]) : [],
    userId: row.userId,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}

/**
 * Plant a batch of USER notes — one per parent×context cell. Note + edge
 * ids are pre-generated by the workflow caller for retry-safety. Returns
 * the same `noteIds` so the orchestrator can pair planted nodes with the
 * Action that will run on each.
 *
 * Layout: USER nodes fan horizontally below their parent — each context
 * gets its own column. Subsequent levels stack further down.
 */
export async function plantUserNodes(input: {
  cells: PlantUserCell[];
  noteIds: string[];
  edgeIds: string[];
  arrangementId: string;
  userId: string;
}): Promise<string[]> {
  const { cells, noteIds, edgeIds, arrangementId, userId } = input;
  if (cells.length === 0) return [];

  const parentIds = Array.from(new Set(cells.map(c => c.parentId)));
  const parents = await services.prisma.note.findMany({
    where: { id: { in: parentIds }, arrangementId },
    select: { id: true, x: true, y: true, layers: true },
  });
  const parentById = new Map(parents.map(p => [p.id, p]));

  const nodesData = cells.map((c, i) => {
    const parent = parentById.get(c.parentId);
    const baseX = parent?.x ?? 0;
    const baseY = parent?.y ?? 0;
    return {
      id: noteIds[i]!,
      arrangementId,
      userId,
      content: c.text,
      type: 'USER' as const,
      status: null,
      x: baseX + c.contextIdx * Canvas.NODE_SPACING.CHILD_SIBLING,
      y: baseY + USER_BELOW_PARENT_Y,
      // Workflow-planted USER nodes inherit their target's layer membership
      // — a workflow run on a layered note shouldn't dump children into the
      // global pile.
      layers: parent?.layers ?? [],
    };
  });

  const edgesData = cells.map((c, i) => ({
    id: edgeIds[i]!,
    ...Edge.childEdgeData(arrangementId, c.parentId, noteIds[i]!),
  }));

  await services.prisma.$transaction(async (tx) => {
    await tx.note.createMany({ data: nodesData, skipDuplicates: true });
    await tx.edge.createMany({ data: edgesData, skipDuplicates: true });
  });

  await emitForCreated({ noteIds, edgeIds, userId });
  return noteIds;
}

/**
 * Create RUNNING ASSISTANT placeholders — one per planted USER node.
 * Action.Job.fill targets these. Returns `noteIds` in input order so the
 * orchestrator can hand them to executeChild.
 *
 * Layout: placeholder hangs directly below its USER parent.
 */
export async function createOptimisticPlaceholders(input: {
  parentIds: string[];
  noteIds: string[];
  edgeIds: string[];
  arrangementId: string;
  userId: string;
  model: string;
}): Promise<string[]> {
  const { parentIds, noteIds, edgeIds, arrangementId, userId, model } = input;
  if (parentIds.length === 0) return [];

  const parents = await services.prisma.note.findMany({
    where: { id: { in: Array.from(new Set(parentIds)) }, arrangementId },
    select: { id: true, x: true, y: true, layers: true },
  });
  const parentById = new Map(parents.map(p => [p.id, p]));

  const nodesData = parentIds.map((parentId, i) => {
    const parent = parentById.get(parentId);
    return {
      id: noteIds[i]!,
      arrangementId,
      userId,
      content: '',
      type: 'ASSISTANT' as const,
      status: 'RUNNING' as const,
      x: parent?.x ?? 0,
      y: (parent?.y ?? 0) + PLACEHOLDER_BELOW_USER_Y,
      assistantProvider: model,
      // Placeholder inherits the just-planted USER's layers (which themselves
      // inherited from the workflow's target), keeping the whole subtree on
      // the same layer as the run's source.
      layers: parent?.layers ?? [],
    };
  });

  const edgesData = parentIds.map((parentId, i) => ({
    id: edgeIds[i]!,
    ...Edge.childEdgeData(arrangementId, parentId, noteIds[i]!),
  }));

  await services.prisma.$transaction(async (tx) => {
    await tx.note.createMany({ data: nodesData, skipDuplicates: true });
    await tx.edge.createMany({ data: edgesData, skipDuplicates: true });
  });

  await emitForCreated({ noteIds, edgeIds, userId });
  return noteIds;
}

/**
 * Re-load the rows we just upserted (skipDuplicates makes the insert
 * return value unreliable on retry) and emit one SSE per pair. Canvas
 * store is LWW-by-id, so retry-emits are harmless.
 */
const emitForCreated = async (input: { noteIds: string[]; edgeIds: string[]; userId: string }) => {
  const [notes, edges] = await Promise.all([
    services.prisma.note.findMany({ where: { id: { in: input.noteIds } } }),
    services.prisma.edge.findMany({ where: { id: { in: input.edgeIds } } }),
  ]);
  const noteById = new Map(notes.map((n: Note.Model) => [n.id, n]));
  const edgeById = new Map(edges.map((e: Edge.Model) => [e.id, e]));
  for (let i = 0; i < input.noteIds.length; i++) {
    const n = noteById.get(input.noteIds[i]!);
    const e = edgeById.get(input.edgeIds[i]!);
    if (n && e) emitNodeCreated(input.userId, n, e);
  }
};
