#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="$(dirname "$0")/../.env"

if [ -f "$ENV_FILE" ]; then
  echo ".env already exists — skipping generation."
  echo "Delete it and re-run to regenerate."
  exit 0
fi

gen() { LC_ALL=C tr -dc 'a-f0-9' < /dev/urandom | head -c 64; }

cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/generate-secrets.sh — do not commit this file.
# Re-run the script to regenerate (delete this file first).

# Required secrets
BETTER_AUTH_SECRET=$(gen)
API_KEY_ENCRYPTION_SECRET=$(gen)
PIANO_DAEMON_TOKEN=$(gen)

# Optional: Google OAuth (leave blank to use email/password only)
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# Optional: set to your public URL when deploying (default: http://localhost:3009)
# PIANO_URL=https://your-domain.example.com
EOF

chmod 600 "$ENV_FILE"
echo "✓ .env created at $ENV_FILE"
echo "  Start the app: docker compose up --build"
